name: stand_app
description: An app that encourages people with desk jobs to live a healthier life.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: "1.1.0+feedbackFix"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  confetti: ^0.5.2
  cupertino_icons: ^0.1.3
  day_night_time_picker: ^0.1.3
  fluttertoast: ^7.0.2
  flutter_vibrate: ^1.0.0
  font_awesome_flutter: ^8.8.1
  flutter_local_notifications:
    path: plugins/flutter_local_notifications
  path_provider: ^1.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: '^0.7.5'

flutter_icons:
  image_path_android: 'icons/app_icon.png'
  image_path_ios: 'icons/app_icon.png'
  android: 'launcher_icon'
  ios: 'launcher_icon_ios'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Light.ttf
        - asset: fonts/RobotoMono-Regular.ttf
